name: spike_view_project
description: A new Flutter application.


dependencies:
  flutter:
    sdk: flutter
  async_loader: "^0.1.1"
  json_annotation: ^0.2.2
  dio: 1.0.3
  shared_preferences: 0.4.2
  intl: "^0.15.6"
  connectivity: "^0.3.1"
  image_picker: "^0.4.8"
  fluttertoast: ^2.0.7
  documents_picker: ^0.0.2
  path_provider: ^0.4.1
  flutter_downloader: 0.1.1
  simple_permissions: ^0.1.5
  url_launcher: "5.0.0"
  share: ^0.5.3
  encrypt: ^0.2.0
  #circle_indicator: ^0.0.7
  #flutter_socket_io: ^0.4.5
  #multiple_image_picker: ^0.4.8
  adhara_socket_io: "0.1.10"
  video_player: ^0.6.0
  chewie: ^0.7.0
  flutter_string_encryption: ^0.2.0
  firebase_messaging: "^3.0.1"
  flutter_local_notifications: "0.4.5"
  image_cropper: ^1.0.0
  spider_chart: "0.1.0"
  dots_indicator: ^0.0.4
  flutter_webview_plugin: ^0.3.3
  keyboard_avoider: ^0.1.2

  rxdart: "0.19.0"
  google_maps_webservice: ^0.0.10
  geocoder: "0.1.0"
  flutter_google_places: "0.1.4+1"


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Boxicons
      fonts:
        - asset: fonts/icomoon.ttf
          weight: 400
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/applogo.png
    - assets/no_message.png
    - assets/filter.png
    - assets/view.png
    - assets/no_feed_new.png

    - assets/splash_bg.png
    - assets/logo_white.png
    - assets/dammy/img1.jpg
    - assets/dammy/profile_sharing_log1.png

  #-----------------------login page Images -----------------------------------#
    - assets/login/login_bg.png
    - assets/login/calander_singup.png
    - assets/login/signup_p_bg.png
    - assets/login/email.png
    - assets/login/password.png
    - assets/login/user.png
    - assets/login/delete.png
    - assets/login/check.png
    - assets/login/forgot_password.png
    - assets/login/change_password.png
    - assets/login/back_arrow.png
  #-----------------------User Profile Images -----------------------------------#
    - assets/profile/background.png
    - assets/profile/user_on_user.png
    - assets/profile/edit_button.png
    - assets/profile/acadamic.png
    - assets/profile/arts.png
    - assets/profile/sports.png
    - assets/profile/Vocational.png
    - assets/profile/circle_camera.png
    - assets/profile/cover_edit.png
    - assets/profile/share_profile.png
    - assets/profile/subscribe.png
    - assets/profile/message_profile.png
    - assets/profile/connect.png
    - assets/profile/connected.png
    - assets/profile/edit.png
    - assets/profile/add.png
    - assets/profile/add_1.png
    - assets/profile/img_default.png
    - assets/profile/less.png
    - assets/profile/less_1.png
    - assets/profile/default_achievement.jpg
    - assets/profile/badges.png
    - assets/profile/certificate.png
    - assets/profile/recommendation.png
    - assets/profile/recommendation_default.png
    - assets/profile/img_default_org.png
    - assets/profile/right_arrow.png
    - assets/profile/plus.png
    - assets/profile/check.png
    - assets/profile/pencil_white.png
    - assets/profile/delet_white.png
    - assets/profile/delete_black.png
    - assets/profile/tick_save.png
    - assets/profile/delete_alert.png
    - assets/profile/achievement.png
    - assets/profile/add_image.png
    - assets/profile/achiv/check.png
    - assets/profile/achiv/uncheck.png
    - assets/profile/education_form_default.png
    - assets/profile/media/certifigate1.png
    - assets/profile/media/badges1.png
    - assets/profile/media/general.png
#-----------------------Parent Images -----------------------------------#
    - assets/profile/parent/plus_black.png
    - assets/profile/parent/active.png
    - assets/profile/parent/inactive.png
    - assets/profile/parent/profile_sharing_log.png
    - assets/profile/parent/p_cros.png

 #-----------------------Navigation Drawer Images -----------------------------------#
    - assets/navigation/change_password.png
    - assets/navigation/noti.png
    - assets/navigation/signout.png
    - assets/navigation/user.png
    - assets/navigation/search.png
    - assets/navigation/add_connection.png
    - assets/navigation/add_message.png
 #-----------------------Navigation Drawer Images -----------------------------------#
    - assets/botombar/connections.png
    - assets/botombar/home.png
    - assets/botombar/message.png
    - assets/botombar/more.png
 #-----------------------Navigation Drawer Images -----------------------------------#
    - assets/profile/user/female.png
    - assets/profile/user/male.png
    - assets/profile/user/na.png
    - assets/profile/user/share_profile1.png
    - assets/profile/user/non_binary.png
    - assets/profile/user/tick.png
    - assets/profile/user/pending.png
    - assets/profile/user/unsubscribe.png
    - assets/profile/user/edit_profile.png
 #-----------------------post Images -----------------------------------#
    - assets/profile/post/all_connections.png
    - assets/profile/post/camera.png
    - assets/profile/post/post.png
    - assets/profile/post/private.png
    - assets/profile/post/public.png
    - assets/profile/post/selected_connections.png
    - assets/profile/post/tagging.png
    - assets/profile/post/video.png
    - assets/profile/post/cross_white.png
    - assets/profile/post/back_arrow_blue.png
    - assets/profile/post/user_more.png
    - assets/profile/post/delete_fill.png
    - assets/profile/post/message_1.png
    - assets/profile/post/unfriend.png
    - assets/profile/post/radio_inactive.png
    - assets/profile/post/radio_selected.png

 #-----------------------Navigation Drawer Images -----------------------------------#
    - assets/home/like.png
    - assets/home/line.png
    - assets/home/comment.png
    - assets/home/share.png
    - assets/home/homei.png
    - assets/home/share_inactive.png
    - assets/home/like_inactive.png
    - assets/home/comment_inactive.png
    - assets/home/send.png
    - assets/home/cancel_white.png
    - assets/home/cover.png
    - assets/home/computer_adding_drafting.png
  #-----------------------SHARE Images -----------------------------------#

    - assets/share/aerial_view.png
    - assets/share/linear_view.png
    - assets/share/share_button.png

  #-----------------------Group Images -----------------------------------#

    - assets/group/group.png
    - assets/group/group_default.png
    - assets/group/create_group_icon.png
    - assets/group/invite.png
    - assets/group/join_group.png
    - assets/group/no_feed.png
    - assets/group/write_post.png
    - assets/group/upload_media.png
    - assets/group/public_toggle.png
    - assets/group/private_toggle.png
    - assets/group/back_arrow.png
    - assets/group/invite_email.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
